### ISSUE TITLE
Dead Repo?

### ISSUE THREAD

**Issue by KiyoIchikawa** [xebialabs-community/xlr-teamcity-plugin#25]
This repository seems to be dead, looking for new maintainers?

I wouldn't mind throwing my hat in to maintain this since my organization is actually using it.

Thoughts @vlussenburg / @sblin / @Jessevanbekkum / @Hes-Siemelink / @angel-git ?

**Comment by angel-git** [comment]
@Hes-Siemelink can we find someone to review the PRs from @KiyoIchikawa  ?

**Comment by KiyoIchikawa** [comment]
Bump?

**Comment by Hes-Siemelink** [comment]
Yes, let's make this work

**Comment by KiyoIchikawa** [comment]
I guess we can close this issue since there does not appear to be any intention of passing ownership of the repo over. Thanks for respodning and your time!
